# Generated by Django 5.1 on 2024-08-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userrefreshtoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserRefreshToken",
        ),
    ]
