# Generated by Django 5.0.6 on 2024-06-23 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('num_beds', models.IntegerField()),
                ('num_baths', models.IntegerField()),
                ('squarft', models.IntegerField()),
                ('contact_num', models.CharField(default='0000000000', max_length=10)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('image', models.ImageField(upload_to='images')),
                ('image1', models.ImageField(upload_to='images')),
                ('image2', models.ImageField(upload_to='images')),
                ('listing_type', models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy')], default='rent', max_length=4)),
                ('favourites', models.ManyToManyField(blank=True, default=False, related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
