# Generated by Django 5.1 on 2024-08-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_property_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="image",
            field=models.ImageField(
                upload_to="https://su1001.pythonanywhere.com/images"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="image1",
            field=models.ImageField(
                upload_to="https://su1001.pythonanywhere.com/images"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="image2",
            field=models.ImageField(
                upload_to="https://su1001.pythonanywhere.com/images"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="listing_type",
            field=models.CharField(max_length=100),
        ),
    ]
